"""Stage-1 quality-control checks.

Each check inspects one aspect of the pipeline output and produces a
:class:`QCFlag` when thresholds are exceeded.  The aggregated result is
a ``qc_summary.json`` / ``qc_summary.md`` that tells the user right
away whether this Stage-1 run is trustworthy and which parts need
careful interpretation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from .dataset import DatasetHandle
from .fingerprints import FingerprintResult
from .orientation import OrientationResult
from .phase import PhaseScreeningResult
from .virtual import VirtualImageResult


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class QCFlag:
    """A single quality-control finding."""

    severity: str  # "info", "warning", "critical"
    code: str
    message: str
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass
class QCResult:
    """Aggregated QC outcome for a Stage-1 run."""

    stage1_status: str  # "PASS" | "PASS_WITH_WARNINGS" | "FAIL"
    n_warnings: int
    n_critical: int
    flags: list[QCFlag] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "stage1_status": self.stage1_status,
            "n_warnings": self.n_warnings,
            "n_critical": self.n_critical,
            "flags": [
                {
                    "severity": flag.severity,
                    "code": flag.code,
                    "message": flag.message,
                    "evidence": flag.evidence,
                }
                for flag in self.flags
            ],
        }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_qc_checks(
    dataset: DatasetHandle | None,
    virtual: VirtualImageResult | None,
    fingerprints: FingerprintResult | None,
    phase: PhaseScreeningResult | None,
    orientation: OrientationResult | None,
    diagnostics: dict[str, Any] | None,
    errors: list[dict[str, Any]] | None,
    *,
    confidence_threshold: float = 0.05,
    sample_mask: np.ndarray | None = None,
) -> QCResult:
    """Run all Stage-1 QC checks and return an aggregated result.

    Parameters
    ----------
    dataset:
        The preprocessed dataset handle (may be ``None`` if loading failed).
    virtual:
        Virtual-image results from Stage 1.
    fingerprints:
        Radial-fingerprint results from Stage 2.
    phase:
        Phase-screening results from Stage 3.
    orientation:
        Orientation-preview results from Stage 4.
    diagnostics:
        Dict of diagnostic output paths / metadata.
    errors:
        List of stage-level errors captured during the run.
    confidence_threshold:
        Threshold used for orientation reliability (same as the workflow
        ``confidence_threshold`` parameter).
    """
    flags: list[QCFlag] = []

    # --- Always-present informational flags --------------------------------
    flags.append(
        QCFlag(
            severity="info",
            code="UNSUPERVISED_LABELS_ONLY",
            message=(
                "Fingerprint-class labels are generated by unsupervised "
                "clustering of radial fingerprints. They are NOT confirmed "
                "crystallographic phases and require Stage-2 validation "
                "(py4DSTEM / pyxem Bragg indexing or template matching)."
            ),
        )
    )

    # --- Upstream errors ---------------------------------------------------
    if errors:
        for err in errors:
            flags.append(
                QCFlag(
                    severity="critical",
                    code="STAGE_ERROR",
                    message=f"Stage '{err.get('stage', 'unknown')}' failed: {err.get('error', 'unknown error')}",
                    evidence={"stage": err.get("stage"), "elapsed_s": err.get("elapsed_s")},
                )
            )

    # --- 1. Input shape ----------------------------------------------------
    _check_input_shape(dataset, flags)

    # --- 2. Virtual images -------------------------------------------------
    _check_virtual_images(virtual, flags)

    # --- 3. Radial fingerprints -------------------------------------------
    _check_radial_fingerprints(fingerprints, flags)

    # --- 4 / 5. Cluster labels + sizes -------------------------------------
    _check_cluster_labels(phase, flags)
    _check_cluster_sizes(phase, flags)

    # --- 6. Beam centre offset ---------------------------------------------
    _check_beam_center(virtual, flags)

    # --- 7. Saturation fraction --------------------------------------------
    _check_saturation(virtual, flags)

    # --- 8. Orientation confidence -----------------------------------------
    _check_orientation_confidence(orientation, confidence_threshold, flags)

    # --- 9. ROI candidates -------------------------------------------------
    _check_roi_candidates(diagnostics, flags)

    # --- 10. Sample mask ----------------------------------------------------
    _check_sample_mask(sample_mask, phase, flags)

    # --- Aggregate ----------------------------------------------------------
    n_critical = sum(1 for f in flags if f.severity == "critical")
    n_warnings = sum(1 for f in flags if f.severity == "warning")

    if n_critical > 0:
        status = "FAIL"
    elif n_warnings > 0:
        status = "PASS_WITH_WARNINGS"
    else:
        status = "PASS"

    return QCResult(
        stage1_status=status,
        n_warnings=n_warnings,
        n_critical=n_critical,
        flags=flags,
    )


def save_qc_summary(output_dir: str | Path, qc_result: QCResult) -> tuple[Path, Path]:
    """Write ``qc_summary.json`` and ``qc_summary.md`` to *output_dir*."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    json_path = out / "qc_summary.json"
    json_path.write_text(
        json.dumps(_jsonable(qc_result.to_dict()), indent=2), encoding="utf-8"
    )

    md_path = out / "qc_summary.md"
    md_path.write_text(_render_qc_markdown(qc_result), encoding="utf-8")

    return json_path, md_path


# ---------------------------------------------------------------------------
# Individual checks
# ---------------------------------------------------------------------------


def _check_input_shape(dataset: DatasetHandle | None, flags: list[QCFlag]) -> None:
    if dataset is None:
        flags.append(
            QCFlag(
                severity="critical",
                code="DATASET_MISSING",
                message="Dataset failed to load. No data available for analysis.",
            )
        )
        return
    shape = dataset.shape
    if len(shape) != 4:
        flags.append(
            QCFlag(
                severity="critical",
                code="INPUT_NOT_4D",
                message=f"Expected 4D-STEM data, got shape {shape}.",
                evidence={"shape": list(shape)},
            )
        )
        return
    nav_y, nav_x, q_y, q_x = shape
    if nav_y < 2 or nav_x < 2:
        flags.append(
            QCFlag(
                severity="critical",
                code="NAVIGATION_TOO_SMALL",
                message=f"Navigation dimensions ({nav_y}, {nav_x}) are too small for meaningful analysis.",
                evidence={"nav_shape": [nav_y, nav_x]},
            )
        )
    if q_y < 4 or q_x < 4:
        flags.append(
            QCFlag(
                severity="warning",
                code="SIGNAL_TOO_SMALL",
                message=f"Detector dimensions ({q_y}, {q_x}) are very small; radial fingerprints may be under-resolved.",
                evidence={"sig_shape": [q_y, q_x]},
            )
        )


def _check_virtual_images(virtual: VirtualImageResult | None, flags: list[QCFlag]) -> None:
    if virtual is None:
        flags.append(
            QCFlag(
                severity="critical",
                code="VIRTUAL_IMAGES_MISSING",
                message="Virtual images were not computed. Downstream results are unavailable.",
            )
        )
        return
    if not virtual.images:
        flags.append(
            QCFlag(
                severity="warning",
                code="VIRTUAL_IMAGES_EMPTY",
                message="Virtual images dict is empty; no virtual detector images were produced.",
            )
        )


def _check_radial_fingerprints(fingerprints: FingerprintResult | None, flags: list[QCFlag]) -> None:
    if fingerprints is None:
        flags.append(
            QCFlag(
                severity="critical",
                code="RADIAL_FINGERPRINTS_MISSING",
                message="Radial fingerprints were not computed.",
            )
        )
        return
    profiles = fingerprints.profiles
    if not np.all(np.isfinite(profiles)):
        n_bad = int(np.sum(~np.isfinite(profiles)))
        flags.append(
            QCFlag(
                severity="warning",
                code="RADIAL_PROFILES_NONFINITE",
                message=f"{n_bad} radial-profile values are non-finite (NaN / Inf).",
                evidence={"non_finite_count": n_bad, "total_values": int(profiles.size)},
            )
        )
    # Check for all-zero profiles (degenerate)
    flat = profiles.reshape(-1, profiles.shape[-1])
    zero_rows = int(np.sum(np.all(flat == 0, axis=1)))
    if zero_rows > 0:
        flags.append(
            QCFlag(
                severity="warning",
                code="RADIAL_PROFILES_ZERO_ROWS",
                message=f"{zero_rows} navigation positions have all-zero radial profiles.",
                evidence={"zero_row_count": zero_rows, "total_rows": flat.shape[0]},
            )
        )


def _check_cluster_labels(phase: PhaseScreeningResult | None, flags: list[QCFlag]) -> None:
    if phase is None:
        flags.append(
            QCFlag(
                severity="critical",
                code="CLUSTER_LABELS_MISSING",
                message="Fingerprint-class labels were not produced.",
            )
        )
        return
    labels = np.asarray(phase.labels)
    unique = np.unique(labels)
    if len(unique) < 2:
        flags.append(
            QCFlag(
                severity="warning",
                code="CLUSTER_SINGLE_CLASS",
                message=f"Only {len(unique)} fingerprint class found; clustering may have failed or the sample is uniform.",
                evidence={"n_classes": int(len(unique))},
            )
        )


def _check_cluster_sizes(phase: PhaseScreeningResult | None, flags: list[QCFlag]) -> None:
    if phase is None:
        return
    labels = np.asarray(phase.labels)
    unique, counts = np.unique(labels, return_counts=True)
    total = max(int(counts.sum()), 1)
    min_frac = float(counts.min() / total) if len(counts) > 0 else 0.0

    if min_frac < 0.01:
        small_cluster = int(unique[int(np.argmin(counts))])
        flags.append(
            QCFlag(
                severity="warning",
                code="CLUSTER_TOO_SMALL",
                message=(
                    f"Cluster {small_cluster} occupies only {min_frac:.3%} of the field of view. "
                    "It may be noise rather than a distinct fingerprint class."
                ),
                evidence={
                    "min_cluster_fraction": round(min_frac, 5),
                    "smallest_cluster_id": small_cluster,
                    "cluster_counts": {int(k): int(v) for k, v in zip(unique, counts)},
                },
            )
        )


def _check_beam_center(virtual: VirtualImageResult | None, flags: list[QCFlag]) -> None:
    if virtual is None:
        return
    try:
        mean_dp = np.asarray(virtual.mean_diffraction, dtype=np.float64)
        yy, xx = np.indices(mean_dp.shape)
        total = max(float(mean_dp.sum()), 1e-12)
        cy = float((mean_dp * yy).sum() / total)
        cx = float((mean_dp * xx).sum() / total)
        rc_y = (mean_dp.shape[0] - 1) / 2
        rc_x = (mean_dp.shape[1] - 1) / 2
        offset = float(np.hypot(cy - rc_y, cx - rc_x))

        if offset > 3:
            flags.append(
                QCFlag(
                    severity="warning",
                    code="BEAM_CENTER_OFFSET",
                    message=(
                        f"Estimated beam centre ({cy:.1f}, {cx:.1f}) is {offset:.1f} px "
                        f"from the geometric centre ({rc_y:.1f}, {rc_x:.1f}). "
                        "Radial fingerprints and diffraction-class labels may be biased."
                    ),
                    evidence={
                        "estimated_center_yx": [round(cy, 3), round(cx, 3)],
                        "radial_center_yx": [round(rc_y, 3), round(rc_x, 3)],
                        "offset_pixels": round(offset, 3),
                    },
                )
            )
    except Exception:
        pass  # best-effort; do not crash the QC pass


def _check_saturation(virtual: VirtualImageResult | None, flags: list[QCFlag]) -> None:
    if virtual is None:
        return
    try:
        max_dp = np.asarray(virtual.max_diffraction, dtype=np.float32)
        saturated = max_dp >= np.percentile(max_dp, 99.9)
        sat_fraction = float(np.mean(saturated))
        if sat_fraction > 0.05:
            flags.append(
                QCFlag(
                    severity="warning",
                    code="SATURATION_HIGH",
                    message=(
                        f"{sat_fraction:.1%} of diffraction patterns show saturation "
                        f"in the 99.9th percentile of the max-diffraction image. "
                        "COM-x / COM-y and radial profiles may be distorted."
                    ),
                    evidence={"saturation_fraction": round(sat_fraction, 5)},
                )
            )
    except Exception:
        pass


def _check_orientation_confidence(
    orientation: OrientationResult | None,
    confidence_threshold: float,
    flags: list[QCFlag],
) -> None:
    if orientation is None:
        return
    try:
        score = np.asarray(orientation.score, dtype=np.float32)
        unreliable = score < confidence_threshold
        unreliable_frac = float(np.mean(unreliable))
        if unreliable_frac > 0.5:
            flags.append(
                QCFlag(
                    severity="warning",
                    code="LOW_ORIENTATION_CONFIDENCE",
                    message=(
                        f"{unreliable_frac:.1%} of orientation-preview positions have "
                        f"scores below the confidence threshold ({confidence_threshold}). "
                        "Orientation preview may be unreliable; consider using templates."
                    ),
                    evidence={
                        "unreliable_fraction": round(unreliable_frac, 5),
                        "confidence_threshold": confidence_threshold,
                    },
                )
            )
    except Exception:
        pass


def _check_roi_candidates(diagnostics: dict[str, Any] | None, flags: list[QCFlag]) -> None:
    if diagnostics is None:
        flags.append(
            QCFlag(
                severity="info",
                code="ROI_CANDIDATES_NOT_GENERATED",
                message="ROI candidates were not generated (diagnostics disabled or failed).",
            )
        )
        return
    roi_outputs = diagnostics.get("roi_outputs", {})
    if not roi_outputs:
        flags.append(
            QCFlag(
                severity="info",
                code="ROI_CANDIDATES_EMPTY",
                message="No ROI candidates were generated. Consider inspecting the cluster and boundary maps manually.",
            )
        )
        return
    # Try to count ROIs from the YAML path.
    yaml_path = roi_outputs.get("yaml")
    if yaml_path and Path(str(yaml_path)).exists():
        try:
            import yaml

            data = yaml.safe_load(Path(str(yaml_path)).read_text(encoding="utf-8"))
            rois = data.get("rois", []) if isinstance(data, dict) else []
            n_rois = len(rois)
            if n_rois == 0:
                flags.append(
                    QCFlag(
                        severity="info",
                        code="ROI_CANDIDATES_EMPTY",
                        message="ROI candidates YAML exists but contains no ROIs.",
                    )
                )
            elif n_rois < 3:
                flags.append(
                    QCFlag(
                        severity="info",
                        code="ROI_CANDIDATES_FEW",
                        message=f"Only {n_rois} ROI candidate(s) found. More ROIs may help Stage-2 coverage.",
                        evidence={"n_rois": n_rois},
                    )
                )
        except Exception:
            pass


def _check_sample_mask(
    sample_mask: np.ndarray | None,
    phase: PhaseScreeningResult | None,
    flags: list[QCFlag],
) -> None:
    if sample_mask is None:
        return
    try:
        sample_frac = float(sample_mask.mean())
        if sample_frac < 0.1:
            flags.append(
                QCFlag(
                    severity="warning",
                    code="SAMPLE_FRACTION_LOW",
                    message=(
                        f"Sample mask covers only {sample_frac:.1%} of the field of view. "
                        "Most of the scan is background / vacuum / excluded."
                    ),
                    evidence={"sample_fraction": round(sample_frac, 5)},
                )
            )

        # Check for background pixels accidentally labeled as sample
        if phase is not None:
            labels = np.asarray(phase.labels)
            n_background = int(np.sum(labels == -1))
            if n_background > 0:
                flags.append(
                    QCFlag(
                        severity="info",
                        code="SAMPLE_MASK_APPLIED",
                        message=(
                            f"Sample mask applied: {int(sample_mask.sum())} sample pixels, "
                            f"{n_background} background pixels (label -1)."
                        ),
                        evidence={
                            "sample_pixels": int(sample_mask.sum()),
                            "background_pixels": n_background,
                            "sample_fraction": round(sample_frac, 5),
                        },
                    )
                )
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render_qc_markdown(result: QCResult) -> str:
    status = result.stage1_status
    emoji = {"PASS": "✅", "PASS_WITH_WARNINGS": "⚠️", "FAIL": "❌"}.get(status, "❓")
    lines = [
        f"# Stage 1 QC Summary",
        "",
        f"**Status: {emoji} {status}**",
        "",
        f"- Warnings: {result.n_warnings}",
        f"- Critical: {result.n_critical}",
        "",
    ]
    if result.flags:
        lines.append("| Severity | Code | Message |")
        lines.append("| --- | --- | --- |")
        for flag in result.flags:
            sev = flag.severity.upper()
            lines.append(f"| `{sev}` | `{flag.code}` | {flag.message} |")
        lines.append("")
    else:
        lines.extend(["_No QC flags._", ""])

    # Interpretation guidance
    lines.extend(
        [
            "## Interpretation Caution",
            "",
            "> The fingerprint-class labels are generated by unsupervised clustering "
            "of radial fingerprints. They should **not** be interpreted as confirmed "
            "crystallographic phases without Stage-2 validation (py4DSTEM / pyxem "
            "Bragg indexing or template matching against candidate CIFs).",
            "",
        ]
    )
    return "\n".join(lines)


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(v) for v in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    return value
